import type { RibbonProps } from './ribbon-types';

/**
 * A minimal, fully-typed `RibbonProps` fixture for mounting `RibbonToolbar` /
 * `MobileToolbar` / `MobileMenuSheet` in tests without having to restate the
 * ~70-field aggregate contract in every spec file. Every callback is a no-op;
 * every piece of state is a sane, inert default (nothing selected, nothing
 * open, edit mode). Pass `overrides` to change just what a test cares about.
 */
export function createRibbonPropsFixture(overrides: Partial<RibbonProps> = {}): RibbonProps {
	const noop = (): void => {};
	const base: RibbonProps = {
		mode: 'edit',
		canEdit: true,
		isNarrowViewport: false,
		isSidebarCollapsed: false,
		isInspectorPaneOpen: false,
		isCompactToolbarOpen: true,
		toolbarSection: 'home',
		scale: 1,
		canUndo: false,
		canRedo: false,
		findReplaceOpen: false,
		selectedElement: null,
		selectedCount: 0,
		editTemplateMode: false,
		newShapeType: 'rect',
		activeTool: 'select',
		drawingColor: '#000000',
		drawingWidth: 2,
		clipboardPayload: null,
		spellCheckEnabled: false,
		showGrid: false,
		showRulers: false,
		showGuides: true,
		snapToGrid: false,
		snapToShape: false,
		isOverflowMenuOpen: false,
		layoutOptions: [],
		customShows: [],
		activeCustomShowId: null,
		isCurrentSlideInActiveShow: false,
		hasMacros: false,
		isThemeEditorOpen: false,
		isThemeGalleryOpen: false,
		canDistribute: false,

		onSetMode: noop,
		onPresentFromBeginning: noop,
		onToggleSidebar: noop,
		onToggleInspector: noop,
		onOpenAnimationPanel: noop,
		onToggleCompactToolbar: noop,
		onSetToolbarSection: noop,
		onZoomIn: noop,
		onZoomOut: noop,
		onZoomToFit: noop,
		onUndo: noop,
		onRedo: noop,
		onToggleFindReplace: noop,
		onSetNewShapeType: noop,
		onAddTextBox: noop,
		onAddShape: noop,
		onAddTable: noop,
		onAddSmartArt: noop,
		onAddEquation: noop,
		onAddActionButton: noop,
		onOpenImagePicker: noop,
		onOpenMediaPicker: noop,
		onSetActiveTool: noop,
		onSetDrawingColor: noop,
		onSetDrawingWidth: noop,
		onSetEditTemplateMode: noop,
		onSetSpellCheckEnabled: noop,
		onSetShowGrid: noop,
		onSetShowRulers: noop,
		onSetShowGuides: noop,
		onSetSnapToGrid: noop,
		onSetSnapToShape: noop,
		onAddGuide: noop,
		onAlignElements: noop,
		onDistributeElements: noop,
		onCopy: noop,
		onCut: noop,
		onPaste: noop,
		onFlip: noop,
		onMoveLayer: noop,
		onMoveLayerToEdge: noop,
		onGroupElements: noop,
		onUngroupElement: noop,
		onUpdateElementStyle: noop,
		onOpenHyperlinkDialog: noop,
		onDuplicate: noop,
		onDelete: noop,
		onCreatePresentation: noop,
		onExportPng: noop,
		onExportPdf: noop,
		onExportVideo: noop,
		onExportGif: noop,
		onExportJson: noop,
		onSaveAsPptx: noop,
		onSaveAsPpsx: noop,
		onSaveAsPptm: noop,
		onCopySlideAsImage: noop,
		onPrint: noop,
		onToggleShortcuts: noop,
		onRunAccessibilityCheck: noop,
		onToggleSlideSorter: noop,
		onOpenReadingView: noop,
		onOpenOutlineView: noop,
		onUpdateTextStyle: noop,
		onTransformTextCase: noop,
		onSetOverflowMenuOpen: noop,
		onInsertSlideFromLayout: noop,
		onInsertSlideFromTemplate: noop,
		onSetActiveCustomShowId: noop,
		onCreateCustomShow: noop,
		onRenameActiveCustomShow: noop,
		onDeleteActiveCustomShow: noop,
		onToggleCurrentSlideInActiveShow: noop,
		onEnterMasterView: noop,
		onCloseMasterView: noop,
		onToggleThemeEditor: noop,
		onToggleThemeGallery: noop,
		onTransitionChange: noop,
		onApplyTransitionToAll: noop,
	};
	return { ...base, ...overrides };
}
