/**
 * Generates `text-style-emphasis.pptx`: a title textbox plus two plain-text
 * boxes, one carrying a `p:set` emphasis targeting `style.fontWeight` (bold),
 * the other targeting `style.color`, each fired by its OWN main-sequence
 * click, for `e2e/text-style-emphasis.spec.ts`.
 *
 * The shared `resolveTextStyleAnimation` (`animation-text-style-resolve.ts`)
 * decodes a `p:set` discrete attribute assignment into a framework-neutral
 * `{ bold, color, ... }` descriptor, and `buildTextStyleOverrideCss`
 * (`animation-text-style-css.ts`) turns it into a scoped
 * `[data-element-id="<id>"] [style] { ... !important }` rule every binding's
 * presentation stage injects. This fixture is the smallest deck that exercises
 * that path without a full authored-in-PowerPoint sample: a real COM-recorded
 * "Bold Reveal" / "Change Font Color" pairing on two separate shapes.
 *
 * WHY this generator post-processes the saved package instead of using the
 * SDK's `addAnimation` (mirrors `generate-smartart-build-fixture.ts`): the
 * simplified SDK animation model authors only whole-element entrances, with no
 * way to express a `p:set` discrete attribute assignment at all.
 *
 *   1. Build a valid base deck via `PptxHandler.createBlank`: a title textbox
 *      plus two plain text boxes, each with an explicit pinned `shapeId` so the
 *      timing tree below can target it via `p:spTgt/@spid` without having to
 *      re-parse the saved XML to discover an auto-minted id.
 *   2. Inject a hand-authored `p:timing` tree: TWO separate click steps, each
 *      mirroring the exact `tmRoot -> mainSeq -> par(delay=indefinite) ->
 *      par(delay=0) -> par(clickEffect)` nesting `generate-smartart-build-
 *      fixture.ts` uses (proven to advance exactly one click per outer
 *      `p:par`) - one `p:set` per step. An earlier version of this generator
 *      nested BOTH `p:set`s as sibling `clickEffect`s under ONE shared outer
 *      wrapper, meaning to fire both on a single click; empirically that
 *      needed THREE clicks to reveal both (an apparent off-by-one in how a
 *      bare-`p:set`-only step, with no `p:animEffect` companion, registers as
 *      "settled" for the next advance), not one. Two independent steps avoid
 *      that entirely and match the proven per-node pattern exactly.
 *
 * Re-runnable; not wired into `global-setup.ts` (its generated bytes are
 * checked in, like `canvas-interaction.pptx` and `connector-arrows.pptx`).
 *
 * Run with: bun run e2e/fixtures/generate-text-style-emphasis-fixture.ts
 */
import { mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import type { PptxElement, TextPptxElement } from 'pptx-viewer-core';
import { PptxHandler, TextBuilder } from 'pptx-viewer-core';

import { writeFixtureDeterministic } from './write-fixture';

const coreRequire = createRequire(createRequire(import.meta.url).resolve('pptx-viewer-core'));
const JSZip = coreRequire('jszip');

const __dirname = dirname(fileURLToPath(import.meta.url));

/** Slide title - the contract the spec navigates by. */
export const TEXT_STYLE_EMPHASIS_TITLE = 'Text Style Emphasis Slide';
/** Text of the shape that gets the `style.fontWeight` (bold) `p:set`. */
export const BOLD_TARGET_TEXT = 'Emphasis Bold Target';
/** Text of the shape that gets the `style.color` `p:set`. */
export const COLOR_TARGET_TEXT = 'Emphasis Color Target';
/** The colour the `style.color` `p:set` assigns (`a:srgbClr`, no `#`). */
export const COLOR_TARGET_HEX = 'FF0000';

const BOLD_SHAPE_ID = '50';
const COLOR_SHAPE_ID = '51';

/** One `p:set` behaviour: `<p:set><p:cBhvr>...</p:cBhvr><p:to>...</p:to></p:set>`. */
function setBehaviorXml(params: {
	behaviorId: number;
	spid: string;
	attrName: string;
	toXml: string;
}): string {
	const { behaviorId, spid, attrName, toXml } = params;
	return (
		`<p:set><p:cBhvr><p:cTn id="${behaviorId}" dur="1" fill="hold"><p:stCondLst><p:cond delay="0"/></p:stCondLst></p:cTn>` +
		`<p:tgtEl><p:spTgt spid="${spid}"/></p:tgtEl>` +
		`<p:attrNameLst><p:attrName>${attrName}</p:attrName></p:attrNameLst></p:cBhvr>` +
		`<p:to>${toXml}</p:to></p:set>`
	);
}

/**
 * One discrete on-click step, mirroring the exact `tmRoot -> mainSeq ->
 * par(delay=indefinite) -> par(delay=0) -> par(clickEffect)` nesting
 * `generate-smartart-build-fixture.ts` uses (proven to advance one click per
 * outer `p:par`): a plain `p:set` needs no `p:animEffect` alongside it, unlike
 * that fixture's diagram reveal.
 */
function clickStepXml(
	ids: readonly [outer: number, inner: number, click: number],
	presetId: number,
	setXml: string,
): string {
	const [outer, inner, click] = ids;
	return (
		`<p:par><p:cTn id="${outer}" fill="hold"><p:stCondLst><p:cond delay="indefinite"/></p:stCondLst><p:childTnLst>` +
		`<p:par><p:cTn id="${inner}" fill="hold"><p:stCondLst><p:cond delay="0"/></p:stCondLst><p:childTnLst>` +
		`<p:par><p:cTn id="${click}" presetID="${presetId}" presetClass="emph" presetSubtype="0" fill="hold" grpId="0" nodeType="clickEffect"><p:stCondLst><p:cond delay="0"/></p:stCondLst><p:childTnLst>` +
		`${setXml}</p:childTnLst></p:cTn></p:par>` +
		`</p:childTnLst></p:cTn></p:par>` +
		`</p:childTnLst></p:cTn></p:par>`
	);
}

/**
 * The full `<p:timing>` tree: TWO separate click steps, one per shape, so the
 * first advance reveals bold and the second reveals colour (each its own
 * click, exactly like `generate-smartart-build-fixture.ts`'s per-node reveal
 * steps - proven to advance one click per outer `p:par`, unlike a single
 * click group holding two sibling `clickEffect` nodes, which this generator
 * tried first and which needed three clicks to fire both, not one).
 */
function timingXml(): string {
	const boldSet = setBehaviorXml({
		behaviorId: 7,
		spid: BOLD_SHAPE_ID,
		attrName: 'style.fontWeight',
		toXml: '<p:strVal val="bold"/>',
	});
	const colorSet = setBehaviorXml({
		behaviorId: 8,
		spid: COLOR_SHAPE_ID,
		attrName: 'style.color',
		toXml: `<p:clrVal><a:srgbClr val="${COLOR_TARGET_HEX}"/></p:clrVal>`,
	});
	const steps = clickStepXml([3, 4, 5], 15, boldSet) + clickStepXml([9, 10, 11], 21, colorSet);
	return (
		`<p:timing><p:tnLst><p:par><p:cTn id="1" dur="indefinite" restart="never" nodeType="tmRoot"><p:childTnLst>` +
		`<p:seq concurrent="1" nextAc="seek"><p:cTn id="2" dur="indefinite" nodeType="mainSeq"><p:childTnLst>` +
		`${steps}</p:childTnLst></p:cTn>` +
		`<p:prevCondLst><p:cond evt="onPrev" delay="0"><p:tgtEl><p:sldTgt/></p:tgtEl></p:cond></p:prevCondLst>` +
		`<p:nextCondLst><p:cond evt="onNext" delay="0"><p:tgtEl><p:sldTgt/></p:tgtEl></p:cond></p:nextCondLst>` +
		`</p:seq></p:childTnLst></p:cTn></p:par></p:tnLst></p:timing>`
	);
}

export async function generateTextStyleEmphasisFixture(): Promise<string> {
	const { handler, data, createSlide } = await PptxHandler.createBlank({
		title: 'Text Style Emphasis Fixture',
		initialSlideCount: 0,
	});

	const boldTarget: TextPptxElement = TextBuilder.create(BOLD_TARGET_TEXT)
		.position(60, 180)
		.size(500, 70)
		.fontSize(28)
		.build();
	boldTarget.shapeId = BOLD_SHAPE_ID;

	const colorTarget: TextPptxElement = TextBuilder.create(COLOR_TARGET_TEXT)
		.position(60, 300)
		.size(500, 70)
		.fontSize(28)
		.build();
	colorTarget.shapeId = COLOR_SHAPE_ID;

	const slideBuilder = createSlide('Blank')
		.addText(TEXT_STYLE_EMPHASIS_TITLE, {
			x: 60,
			y: 60,
			width: 600,
			height: 80,
			fontSize: 32,
			bold: true,
		})
		.addElement(boldTarget as PptxElement)
		.addElement(colorTarget as PptxElement);
	data.slides.push(slideBuilder.build());

	const baseBytes = await handler.save(data.slides);
	const zip = await JSZip.loadAsync(baseBytes);

	const slidePath = 'ppt/slides/slide1.xml';
	const slideXmlFile = zip.file(slidePath);
	if (!slideXmlFile) {
		throw new Error(`${slidePath} missing from the saved package`);
	}
	const slideXml = await slideXmlFile.async('string');
	if (!slideXml.includes('</p:sld>')) {
		throw new Error(`${slidePath} has no </p:sld> closing tag to inject p:timing before`);
	}
	zip.file(slidePath, slideXml.replace('</p:sld>', `${timingXml()}</p:sld>`));

	const bytes: Uint8Array = await zip.generateAsync({
		type: 'uint8array',
		compression: 'DEFLATE',
		compressionOptions: { level: 9 },
	});

	const outPath = resolve(__dirname, 'text-style-emphasis.pptx');
	mkdirSync(dirname(outPath), { recursive: true });
	await writeFixtureDeterministic(outPath, bytes);
	return outPath;
}

const invokedDirectly =
	typeof process !== 'undefined' &&
	process.argv[1] &&
	process.argv[1].endsWith('generate-text-style-emphasis-fixture.ts');
if (invokedDirectly) {
	generateTextStyleEmphasisFixture()
		.then((p) => console.log(`Wrote ${p}`))
		.catch((err) => {
			console.error(err);
			process.exit(1);
		});
}
