/**
 * Generates `pixelate-filter.pptx`: a title textbox plus one colourful
 * gradient-filled rectangle whose entrance is a bare `p:animEffect
 * filter="pixelate" transition="in"` with NO `presetID`/`presetClass` on its
 * `clickEffect` `p:cTn` - the shape a non-PowerPoint authoring tool is likely
 * to emit, and exactly the scenario `resolveFilterEffect`'s fallback path
 * (`packages/shared/src/render/animation-filter-effects.ts`) exists for (see
 * `PptxNativeAnimationService.animeffect-filter.test.ts` for the parser-level
 * proof of this shape). Used by `e2e/animation-pixelate-filter.spec.ts` to pin
 * that every binding actually plays the mosaic `pixelateIn` keyframes (built
 * from the self-contained SVG `<filter>` data-URIs in
 * `render/animation-pixelate-filter.ts`), not the neutral fade fallback.
 *
 * WHY this generator post-processes the saved package instead of using the
 * SDK's `addAnimation` (mirrors `generate-text-style-emphasis-fixture.ts` /
 * `generate-smartart-build-fixture.ts`): the simplified SDK animation model
 * has no way to author a raw `@filter` string with no recognised preset id.
 *
 * Re-runnable; not wired into `global-setup.ts` (its generated bytes are
 * checked in, like `text-style-emphasis.pptx`).
 *
 * Run with: bun run e2e/fixtures/generate-pixelate-filter-fixture.ts
 */
import { mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import type { PptxElement } from 'pptx-viewer-core';
import { PptxHandler, ShapeBuilder } from 'pptx-viewer-core';

import { writeFixtureDeterministic } from './write-fixture';

const coreRequire = createRequire(createRequire(import.meta.url).resolve('pptx-viewer-core'));
const JSZip = coreRequire('jszip');

const __dirname = dirname(fileURLToPath(import.meta.url));

/** Slide title - the contract the spec navigates by. */
export const PIXELATE_FIXTURE_TITLE = 'Pixelate Filter Fixture';
/** Native OOXML shape id (`p:cNvPr/@id`) pinned on the gradient rectangle. */
export const PIXELATE_TARGET_SHAPE_ID = '60';

/**
 * One discrete on-click entrance step, mirroring the exact `tmRoot ->
 * mainSeq -> par(delay=indefinite) -> par(delay=0) -> par(clickEffect)`
 * nesting `generate-smartart-build-fixture.ts` uses (proven to advance one
 * click per outer `p:par`). The `clickEffect` `p:cTn` deliberately carries NO
 * `presetID`/`presetClass`, so `p:animEffect/@filter` is the ONLY signal
 * `resolveEffect` has to work with.
 */
function pixelateClickStepXml(ids: readonly [outer: number, inner: number, click: number]): string {
	const [outer, inner, click] = ids;
	const spTgt = `<p:spTgt spid="${PIXELATE_TARGET_SHAPE_ID}"/>`;
	return (
		`<p:par><p:cTn id="${outer}" fill="hold"><p:stCondLst><p:cond delay="indefinite"/></p:stCondLst><p:childTnLst>` +
		`<p:par><p:cTn id="${inner}" fill="hold"><p:stCondLst><p:cond delay="0"/></p:stCondLst><p:childTnLst>` +
		`<p:par><p:cTn id="${click}" fill="hold" grpId="0" nodeType="clickEffect"><p:stCondLst><p:cond delay="0"/></p:stCondLst><p:childTnLst>` +
		`<p:animEffect transition="in" filter="pixelate"><p:cBhvr><p:cTn id="${click + 1}" dur="800"/><p:tgtEl>${spTgt}</p:tgtEl></p:cBhvr></p:animEffect>` +
		`</p:childTnLst></p:cTn></p:par>` +
		`</p:childTnLst></p:cTn></p:par>` +
		`</p:childTnLst></p:cTn></p:par>`
	);
}

/** The full `<p:timing>` tree: one click step firing the pixelate entrance. */
function timingXml(): string {
	const step = pixelateClickStepXml([3, 4, 5]);
	return (
		`<p:timing><p:tnLst><p:par><p:cTn id="1" dur="indefinite" restart="never" nodeType="tmRoot"><p:childTnLst>` +
		`<p:seq concurrent="1" nextAc="seek"><p:cTn id="2" dur="indefinite" nodeType="mainSeq"><p:childTnLst>` +
		`${step}</p:childTnLst></p:cTn>` +
		`<p:prevCondLst><p:cond evt="onPrev" delay="0"><p:tgtEl><p:sldTgt/></p:tgtEl></p:cond></p:prevCondLst>` +
		`<p:nextCondLst><p:cond evt="onNext" delay="0"><p:tgtEl><p:sldTgt/></p:tgtEl></p:cond></p:nextCondLst>` +
		`</p:seq></p:childTnLst></p:cTn></p:par></p:tnLst></p:timing>`
	);
}

export async function generatePixelateFilterFixture(): Promise<string> {
	const { handler, data, createSlide } = await PptxHandler.createBlank({
		title: 'Pixelate Filter Fixture',
		initialSlideCount: 0,
	});

	// A multi-stop diagonal gradient so the mosaic's blocky cells are visibly
	// distinct from a plain flat fill in a screenshot.
	const target = ShapeBuilder.create('rect')
		.position(60, 160)
		.size(500, 300)
		.gradientFill(
			[
				{ color: '#FF0000', position: 0 },
				{ color: '#FFFF00', position: 0.25 },
				{ color: '#00FF00', position: 0.5 },
				{ color: '#00FFFF', position: 0.75 },
				{ color: '#0000FF', position: 1 },
			],
			45,
		)
		.build();
	target.shapeId = PIXELATE_TARGET_SHAPE_ID;

	const slideBuilder = createSlide('Blank')
		.addText(PIXELATE_FIXTURE_TITLE, {
			x: 60,
			y: 60,
			width: 600,
			height: 80,
			fontSize: 32,
			bold: true,
		})
		.addElement(target as PptxElement);
	data.slides.push(slideBuilder.build());

	const baseBytes = await handler.save(data.slides);
	const zip = await JSZip.loadAsync(baseBytes);

	const slidePath = 'ppt/slides/slide1.xml';
	const slideXmlFile = zip.file(slidePath);
	if (!slideXmlFile) {
		throw new Error(`${slidePath} missing from the saved package`);
	}
	const slideXml = await slideXmlFile.async('string');
	if (!slideXml.includes('</p:sld>')) {
		throw new Error(`${slidePath} has no </p:sld> closing tag to inject p:timing before`);
	}
	zip.file(slidePath, slideXml.replace('</p:sld>', `${timingXml()}</p:sld>`));

	const bytes: Uint8Array = await zip.generateAsync({
		type: 'uint8array',
		compression: 'DEFLATE',
		compressionOptions: { level: 9 },
	});

	const outPath = resolve(__dirname, 'pixelate-filter.pptx');
	mkdirSync(dirname(outPath), { recursive: true });
	await writeFixtureDeterministic(outPath, bytes);
	return outPath;
}

const invokedDirectly =
	typeof process !== 'undefined' &&
	process.argv[1] &&
	process.argv[1].endsWith('generate-pixelate-filter-fixture.ts');
if (invokedDirectly) {
	generatePixelateFilterFixture()
		.then((p) => console.log(`Wrote ${p}`))
		.catch((err) => {
			console.error(err);
			process.exit(1);
		});
}
