import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import {
	PRESENTATION_FIELD_NAMES,
	deserializePptxFromJson,
	serializePptxToJson,
} from '../../converter/json';
import { PptxHandler } from '../../core/PptxHandler';
import type { PptxData } from '../../core/types';

const fixture = fileURLToPath(
	new URL('../../../../../e2e/fixtures/sample-deck.pptx', import.meta.url),
);

async function loadFixture(): Promise<PptxData | null> {
	// The fixture is generated by the e2e setup and committed to the repo;
	// skip defensively if a checkout lacks it rather than failing.
	if (!existsSync(fixture)) {
		return null;
	}
	const bytes = readFileSync(fixture);
	const handler = new PptxHandler();
	return handler.load(bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength));
}

function presentationFields(data: PptxData): Record<string, unknown> {
	const source = data as unknown as Record<string, unknown>;
	const picked: Record<string, unknown> = {};
	for (const key of PRESENTATION_FIELD_NAMES) {
		if (source[key] !== undefined) {
			picked[key] = source[key];
		}
	}
	return picked;
}

describe('pptx-viewer-json round-trip (real fixture)', () => {
	it('toJson -> fromJson preserves model equality for a real deck', async () => {
		const data = await loadFixture();
		if (!data) {
			return;
		}

		const json = serializePptxToJson(data);
		const rebuilt = deserializePptxFromJson(json);

		expect(rebuilt.slides).toHaveLength(data.slides.length);
		// `toEqual` (not `toStrictEqual`) is deliberate: the loader emits keys
		// holding an explicit `undefined`, which JSON cannot represent; dropping
		// them is semantically lossless and the only difference after re-import.
		/* oxlint-disable-next-line vitest/prefer-strict-equal */
		expect(rebuilt.slides).toEqual(data.slides);
		/* oxlint-disable-next-line vitest/prefer-strict-equal */
		expect(presentationFields(rebuilt)).toEqual(presentationFields(data));
	});

	it('loads pptx-viewer-json bytes directly through the handler', async () => {
		const data = await loadFixture();
		if (!data) {
			return;
		}

		const json = serializePptxToJson(data);
		const jsonBytes = new TextEncoder().encode(json);
		const handler = new PptxHandler();
		const imported = await handler.load(
			jsonBytes.buffer.slice(jsonBytes.byteOffset, jsonBytes.byteOffset + jsonBytes.byteLength),
		);

		expect(imported.slides).toHaveLength(data.slides.length);
		expect(imported.width).toBe(data.width);
		expect(imported.height).toBe(data.height);
		// See above: explicit-`undefined` keys from the loader are dropped by JSON.
		/* oxlint-disable-next-line vitest/prefer-strict-equal */
		expect(imported.slides).toEqual(data.slides);

		// The imported deck stays saveable without the original archive.
		const saved = await handler.save(imported.slides);
		expect(saved.byteLength).toBeGreaterThan(0);
	});
});
