/**
 * MSOSPT (OfficeArt shape type, [MS-ODRAW] 2.4.24) to ECMA-376 preset
 * geometry name mapping.
 *
 * The generated PPTX uses standard ST_ShapeType names, which the existing
 * geometry engine (200+ presets) renders. Unknown types fall back to "rect".
 *
 * @module ppt/escher/geometry-map
 */

/** Shape types that render as connectors ("cxnSp") in the PPTX output. */
export const CONNECTOR_TYPES: ReadonlyMap<number, string> = new Map([
	[20, 'line'],
	[32, 'straightConnector1'],
	[33, 'bentConnector2'],
	[34, 'bentConnector3'],
	[35, 'bentConnector4'],
	[36, 'bentConnector5'],
	[37, 'curvedConnector2'],
	[38, 'curvedConnector3'],
	[39, 'curvedConnector4'],
	[40, 'curvedConnector5'],
]);

const SHAPE_TYPES: ReadonlyMap<number, string> = new Map([
	[1, 'rect'],
	[2, 'roundRect'],
	[3, 'ellipse'],
	[4, 'diamond'],
	[5, 'triangle'],
	[6, 'rtTriangle'],
	[7, 'parallelogram'],
	[8, 'trapezoid'],
	[9, 'hexagon'],
	[10, 'octagon'],
	[11, 'plus'],
	[12, 'star5'],
	[13, 'rightArrow'],
	[15, 'homePlate'],
	[16, 'cube'],
	[19, 'arc'],
	[21, 'plaque'],
	[22, 'can'],
	[23, 'donut'],
	[41, 'callout1'],
	[42, 'callout2'],
	[43, 'callout3'],
	[44, 'accentCallout1'],
	[45, 'accentCallout2'],
	[46, 'accentCallout3'],
	[47, 'borderCallout1'],
	[48, 'borderCallout2'],
	[49, 'borderCallout3'],
	[53, 'ribbon'],
	[54, 'ribbon2'],
	[55, 'chevron'],
	[56, 'pentagon'],
	[57, 'noSmoking'],
	[58, 'star8'],
	[59, 'star16'],
	[60, 'star32'],
	[61, 'wedgeRectCallout'],
	[62, 'wedgeRoundRectCallout'],
	[63, 'wedgeEllipseCallout'],
	[64, 'wave'],
	[65, 'foldedCorner'],
	[66, 'leftArrow'],
	[67, 'downArrow'],
	[68, 'upArrow'],
	[69, 'leftRightArrow'],
	[70, 'upDownArrow'],
	[71, 'irregularSeal1'],
	[72, 'irregularSeal2'],
	[73, 'lightningBolt'],
	[74, 'heart'],
	[76, 'quadArrow'],
	[77, 'leftArrowCallout'],
	[78, 'rightArrowCallout'],
	[79, 'upArrowCallout'],
	[80, 'downArrowCallout'],
	[81, 'leftRightArrowCallout'],
	[82, 'upDownArrowCallout'],
	[83, 'quadArrowCallout'],
	[84, 'bevel'],
	[85, 'leftBracket'],
	[86, 'rightBracket'],
	[87, 'leftBrace'],
	[88, 'rightBrace'],
	[89, 'leftUpArrow'],
	[90, 'bentUpArrow'],
	[91, 'bentArrow'],
	[92, 'star24'],
	[93, 'stripedRightArrow'],
	[94, 'notchedRightArrow'],
	[95, 'blockArc'],
	[96, 'smileyFace'],
	[97, 'verticalScroll'],
	[98, 'horizontalScroll'],
	[99, 'circularArrow'],
	[101, 'uturnArrow'],
	[102, 'curvedRightArrow'],
	[103, 'curvedLeftArrow'],
	[104, 'curvedUpArrow'],
	[105, 'curvedDownArrow'],
	[106, 'cloudCallout'],
	[107, 'ellipseRibbon'],
	[108, 'ellipseRibbon2'],
	[109, 'flowChartProcess'],
	[110, 'flowChartDecision'],
	[111, 'flowChartInputOutput'],
	[112, 'flowChartPredefinedProcess'],
	[113, 'flowChartInternalStorage'],
	[114, 'flowChartDocument'],
	[115, 'flowChartMultidocument'],
	[116, 'flowChartTerminator'],
	[117, 'flowChartPreparation'],
	[118, 'flowChartManualInput'],
	[119, 'flowChartManualOperation'],
	[120, 'flowChartConnector'],
	[121, 'flowChartPunchedCard'],
	[122, 'flowChartPunchedTape'],
	[123, 'flowChartSummingJunction'],
	[124, 'flowChartOr'],
	[125, 'flowChartCollate'],
	[126, 'flowChartSort'],
	[127, 'flowChartExtract'],
	[128, 'flowChartMerge'],
	[130, 'flowChartOnlineStorage'],
	[131, 'flowChartMagneticTape'],
	[132, 'flowChartMagneticDisk'],
	[133, 'flowChartMagneticDrum'],
	[134, 'flowChartDisplay'],
	[135, 'flowChartDelay'],
	[176, 'flowChartAlternateProcess'],
	[177, 'flowChartOffpageConnector'],
	[178, 'callout1'],
	[179, 'accentCallout1'],
	[180, 'borderCallout1'],
	[182, 'leftRightUpArrow'],
	[183, 'sun'],
	[184, 'moon'],
	[185, 'bracketPair'],
	[186, 'bracePair'],
	[187, 'star4'],
	[188, 'doubleWave'],
	[189, 'actionButtonBlank'],
	[190, 'actionButtonHome'],
	[191, 'actionButtonHelp'],
	[192, 'actionButtonInformation'],
	[193, 'actionButtonForwardNext'],
	[194, 'actionButtonBackPrevious'],
	[195, 'actionButtonEnd'],
	[196, 'actionButtonBeginning'],
	[197, 'actionButtonReturn'],
	[198, 'actionButtonDocument'],
	[199, 'actionButtonSound'],
	[200, 'actionButtonMovie'],
	[202, 'rect'], // msosptTextBox
]);

/**
 * Map an MSOSPT value to a preset geometry name.
 *
 * @param spt - The OfficeArt shape type from the FSP record instance.
 * @returns Preset name; unknown types fall back to "rect".
 */
export function presetForShapeType(spt: number): string {
	return CONNECTOR_TYPES.get(spt) ?? SHAPE_TYPES.get(spt) ?? 'rect';
}

/** True when the shape type is a text box. */
export function isTextBoxType(spt: number): boolean {
	return spt === 202;
}
