/**
 * CFB / OLE2 reader tests against a real PowerPoint 97-2003 compound file
 * (generated by PowerPoint via COM automation from e2e/fixtures decks).
 */
import { readFileSync } from 'node:fs';
import path from 'node:path';

import { describe, expect, it } from 'vitest';

import { Ole2ParseError, parseOle2 } from './ole2-parser';

const FIXTURES = path.resolve(__dirname, '../../__tests__/fixtures');

function loadFixture(name: string): ArrayBuffer {
	const buf = readFileSync(path.join(FIXTURES, name));
	return buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength) as ArrayBuffer;
}

describe('parseOle2 (read path, real .ppt compound files)', () => {
	it('reads the directory of a real .ppt file', () => {
		const ole = parseOle2(loadFixture('sample-deck.ppt'));
		const names = ole.entries.map((e) => e.name);
		expect(names).toContain('Current User');
		expect(names).toContain('PowerPoint Document');
	});

	it('extracts regular FAT streams with correct sizes', () => {
		const ole = parseOle2(loadFixture('sample-deck.ppt'));
		const doc = ole.getStream('PowerPoint Document');
		expect(doc).toBeDefined();
		const entry = ole.entries.find((e) => e.name === 'PowerPoint Document');
		expect(doc).toHaveLength(entry?.size ?? -1);
		expect(doc && doc.length).toBeGreaterThan(10000);
	});

	it('extracts the Pictures stream when present', () => {
		const ole = parseOle2(loadFixture('picture-fixture.ppt'));
		const pictures = ole.getStream('Pictures');
		expect(pictures).toBeDefined();
		expect(pictures && pictures.length).toBeGreaterThan(0);
	});

	it('returns undefined for missing streams', () => {
		const ole = parseOle2(loadFixture('sample-deck.ppt'));
		expect(ole.getStream('No Such Stream')).toBeUndefined();
	});

	it('rejects non-OLE2 input', () => {
		const zipMagic = new Uint8Array([0x50, 0x4b, 0x03, 0x04, 0, 0, 0, 0, 0, 0, 0, 0]);
		expect(() => parseOle2(zipMagic.buffer as ArrayBuffer)).toThrow(Ole2ParseError);
	});
});
