/**
 * Enum token sets for `a:bodyPr/a:scene3d` camera preset / light rig / light
 * direction validation, shared by {@link ../text-body-scene3d}'s parse and
 * save paths. Split out purely to keep that file under the repo's LOC
 * guideline.
 *
 * @module core/utils/text-body-scene3d-presets
 */

export const CAMERA_PRESETS = new Set([
	'legacyObliqueTopLeft',
	'legacyObliqueTop',
	'legacyObliqueTopRight',
	'legacyObliqueLeft',
	'legacyObliqueFront',
	'legacyObliqueRight',
	'legacyObliqueBottomLeft',
	'legacyObliqueBottom',
	'legacyObliqueBottomRight',
	'legacyPerspectiveTopLeft',
	'legacyPerspectiveTop',
	'legacyPerspectiveTopRight',
	'legacyPerspectiveLeft',
	'legacyPerspectiveFront',
	'legacyPerspectiveRight',
	'legacyPerspectiveBottomLeft',
	'legacyPerspectiveBottom',
	'legacyPerspectiveBottomRight',
	'orthographicFront',
	'isometricTopUp',
	'isometricTopDown',
	'isometricBottomUp',
	'isometricBottomDown',
	'isometricLeftUp',
	'isometricLeftDown',
	'isometricRightUp',
	'isometricRightDown',
	'isometricOffAxis1Left',
	'isometricOffAxis1Right',
	'isometricOffAxis1Top',
	'isometricOffAxis2Left',
	'isometricOffAxis2Right',
	'isometricOffAxis2Top',
	'isometricOffAxis3Left',
	'isometricOffAxis3Right',
	'isometricOffAxis3Bottom',
	'isometricOffAxis4Left',
	'isometricOffAxis4Right',
	'isometricOffAxis4Bottom',
	'obliqueTopLeft',
	'obliqueTop',
	'obliqueTopRight',
	'obliqueLeft',
	'obliqueRight',
	'obliqueBottomLeft',
	'obliqueBottom',
	'obliqueBottomRight',
	'perspectiveFront',
	'perspectiveLeft',
	'perspectiveRight',
	'perspectiveAbove',
	'perspectiveBelow',
	'perspectiveAboveLeftFacing',
	'perspectiveAboveRightFacing',
	'perspectiveContrastingLeftFacing',
	'perspectiveContrastingRightFacing',
	'perspectiveHeroicLeftFacing',
	'perspectiveHeroicRightFacing',
	'perspectiveHeroicExtremeLeftFacing',
	'perspectiveHeroicExtremeRightFacing',
	'perspectiveRelaxed',
	'perspectiveRelaxedModerately',
]);

export const LIGHT_RIGS = new Set([
	'legacyFlat1',
	'legacyFlat2',
	'legacyFlat3',
	'legacyFlat4',
	'legacyNormal1',
	'legacyNormal2',
	'legacyNormal3',
	'legacyNormal4',
	'legacyHarsh1',
	'legacyHarsh2',
	'legacyHarsh3',
	'legacyHarsh4',
	'threePt',
	'balanced',
	'soft',
	'harsh',
	'flood',
	'contrasting',
	'morning',
	'sunrise',
	'sunset',
	'chilly',
	'freezing',
	'flat',
	'twoPt',
	'glow',
	'brightRoom',
]);

export const LIGHT_DIRECTIONS = new Set(['tl', 't', 'tr', 'l', 'r', 'bl', 'b', 'br']);
