/**
 * Table-style part precedence (ECMA-376 §21.1.3.14) and the built-in style
 * catalogue.
 *
 * GROUND TRUTH: PowerPoint 16.0 was driven over COM to render a 4x4 table with
 * "Dark Style 1 - Accent 1" and both `firstRow` and `firstCol` enabled, then
 * the exported PNG was sampled:
 *
 *   header row x first column -> #000000  (dk1        = the firstRow fill)
 *   header row x other column -> #000000  (dk1        = the firstRow fill)
 *   body row   x first column -> #0E4B66  (accent1 shaded = the firstCol fill)
 *   body row   x other column -> #156082  (accent1     = the wholeTbl fill)
 *
 * So the ROW part outranks the COLUMN part where they cross. These tests fail
 * under either wrong order: applying firstCol after firstRow paints the
 * top-left cell the first-column colour, and applying the parts in a sequence
 * that drops firstCol entirely leaves the body-row first column unpainted.
 */
import type { ParsedTableStyleMap, PptxTableData, PptxThemeColorScheme } from 'pptx-viewer-core';
import { describe, it, expect } from 'vitest';

import { getTableCellBandStyle, resolveTableStyleEntry } from './table-style';
import { resolveCellBorderCss } from './table-style-borders';
import { getBuiltinTableStyle, builtinTableStyleMap } from './table-style-builtins';

/** "Dark Style 1 - Accent 1": firstRow = dk1, firstCol = accent1 shade 60%. */
const DARK_STYLE_1_ACCENT_1 = '{125E5076-3810-47DD-B79F-674D7AD40C01}';
/** "Medium Style 2 - Accent 1", the style PowerPoint uses as the deck default. */
const MEDIUM_STYLE_2_ACCENT_1 = '{5C22544A-7EE6-4342-B048-85BDC9FD1C3A}';

/** Matches the Office theme PowerPoint rendered the ground-truth deck with. */
const colorScheme = {
	dk1: '#000000',
	lt1: '#FFFFFF',
	dk2: '#0E2841',
	lt2: '#E8E8E8',
	accent1: '#156082',
	accent2: '#E97132',
	accent3: '#196B24',
	accent4: '#0F9ED5',
	accent5: '#A02B93',
	accent6: '#4EA72E',
} as unknown as PptxThemeColorScheme;

function darkStyle1Table(): PptxTableData {
	return {
		rows: [],
		columnWidths: [0.25, 0.25, 0.25, 0.25],
		tableStyleId: DARK_STYLE_1_ACCENT_1,
		firstRowHeader: true,
		firstCol: true,
	};
}

const at = (row: number, col: number, tableStyleMap?: ParsedTableStyleMap) =>
	getTableCellBandStyle(darkStyle1Table(), row, col, 4, 4, { colorScheme, tableStyleMap });

describe('built-in table style catalogue (F6)', () => {
	it('resolves all 74 of PowerPoint’s built-in style GUIDs', () => {
		expect(Object.keys(builtinTableStyleMap())).toHaveLength(74);
	});

	it('names a built-in style exactly as PowerPoint does', () => {
		expect(getBuiltinTableStyle(MEDIUM_STYLE_2_ACCENT_1)?.styleName).toBe(
			'Medium Style 2 - Accent 1',
		);
		expect(getBuiltinTableStyle(DARK_STYLE_1_ACCENT_1)?.styleName).toBe('Dark Style 1 - Accent 1');
	});

	it('derives every accent variant of a family from its template', () => {
		// "Medium Style 2 - Accent 4" is generated by substitution, not stored.
		const accent4 = getBuiltinTableStyle('{00A15C55-8517-42AA-B614-E9B94910E393}');
		expect(accent4?.styleName).toBe('Medium Style 2 - Accent 4');
		expect(accent4?.firstRowFill).toStrictEqual({ schemeColor: 'accent4' });
		expect(accent4?.wholeTblFill).toStrictEqual({ schemeColor: 'accent4', tint: 20000 });
		// ...and does not leak the template's own accent anywhere.
		expect(JSON.stringify(accent4)).not.toContain('accent1');
	});

	it('accepts an unbraced / lower-case GUID', () => {
		expect(getBuiltinTableStyle('125e5076-3810-47dd-b79f-674d7ad40c01')?.styleName).toBe(
			'Dark Style 1 - Accent 1',
		);
	});

	it('lets a deck-authored entry of the same GUID win over the built-in', () => {
		const map: ParsedTableStyleMap = {
			[MEDIUM_STYLE_2_ACCENT_1]: {
				styleId: MEDIUM_STYLE_2_ACCENT_1,
				styleName: 'Customised',
				firstRowFill: { schemeColor: 'accent6' },
			},
		};
		expect(resolveTableStyleEntry(MEDIUM_STYLE_2_ACCENT_1, map)?.styleName).toBe('Customised');
	});

	it('paints a themed table from the catalogue when the deck defines no styles', () => {
		// Before the catalogue existed this GUID resolved to `undefined` and the
		// header fell through to the hardcoded rgba(68, 114, 196, 0.85) blue.
		const header = at(0, 1);
		expect(header?.backgroundColor).toBe('#000000');
		expect(header?.backgroundColor).not.toBe('rgba(68, 114, 196, 0.85)');
	});
});

describe('table-style part precedence (F4)', () => {
	it('gives the header row precedence over the first column where they cross', () => {
		// PowerPoint ground truth: #000000 (dk1), NOT the first-column fill.
		expect(at(0, 0)?.backgroundColor).toBe('#000000');
	});

	it('still paints the first column in a body row', () => {
		// accent1 #156082 shaded 60% -> the firstCol fill, distinct from the
		// wholeTbl fill. PowerPoint renders #0E4B66 here; we produce #0D3A4E
		// because our shade math is done in sRGB rather than linear RGB. That
		// gap is a separate colour-transform issue; what this asserts is that
		// the FIRST-COLUMN part is the one being applied at all.
		const cell = at(1, 0);
		expect(cell?.backgroundColor).not.toBe('#156082');
		expect(cell?.backgroundColor).toBe('#0D3A4E');
	});

	it('paints an ordinary body cell with the whole-table fill', () => {
		expect(at(1, 1)?.backgroundColor).toBe('#156082');
	});

	it('paints an ordinary header cell with the header fill', () => {
		expect(at(0, 1)?.backgroundColor).toBe('#000000');
	});

	it('orders the border cascade the same way, corners included', () => {
		const entry = getBuiltinTableStyle(DARK_STYLE_1_ACCENT_1);
		const resolve = (fill: { schemeColor: string } | undefined) =>
			fill?.schemeColor === 'lt1' ? '#FFFFFF' : undefined;
		// Dark Style 1 gives firstRow a 3px bottom rule and firstCol a 3px right
		// rule, then cancels the right rule on the nwCell corner. The corner is
		// the LAST part in the sequence, so it must win over firstCol.
		const topLeft = resolveCellBorderCss(
			entry,
			darkStyle1Table(),
			{ rowIndex: 0, cellIndex: 0, rowCount: 4, columnCount: 4 },
			resolve,
		);
		expect(topLeft?.borderRight).toBe('none');
		expect(topLeft?.borderBottom).toBe('3px solid #FFFFFF');
		// One row down there is no corner, so the first column's rule survives.
		const bodyLeft = resolveCellBorderCss(
			entry,
			darkStyle1Table(),
			{ rowIndex: 1, cellIndex: 0, rowCount: 4, columnCount: 4 },
			resolve,
		);
		expect(bodyLeft?.borderRight).toBe('3px solid #FFFFFF');
	});
});
